shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 30.0
controller_patience: 15.0
conservative_reset_dist: 0.5
planner_frequency: 0.1
oscillation_timeout: 10.0
oscillation_distance: 0.2






DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.7     #0.20
  min_vel_x: -0.7

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.7
  min_vel_trans:  0.05    #0.2      #0.05

  max_vel_theta: 2.5  #2.5
  min_vel_theta: 0.2  #0.2

  acc_lim_x: 2.5 #2.5   
  acc_lim_y: 0.0
  acc_lim_theta: 3.5  #3.2  #3.5

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.2      #0.1                #0.05
  yaw_goal_tolerance: 1.0     #0.5             # 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.05
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  forward_point_distance: 0.5
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.20
  prune_plan: true

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true


