footprint: [[-0.515, -0.275], [-0.515, 0.275],[0.125, 0.275],[0.125, -0.275]]
#robot_radius: ir_of_robot
footprint_padding: 0.02

inflation_layer: 
  cost_scaling_factor: 3.0 
  inflation_radius: 1.2
obstacle_range: 3.5
#raytrace_range: 6.0

obstacle_layer:
  observation_sources: laser 
  laser: 
    clearing: true
    data_type: LaserScan
    inf_is_valid: true
    marking: true
    topic: scan