header:
  seq: 1
  stamp:
    secs: 0
    nsecs:         0
  frame_id: 'map'
poses:
  -
    header:
      seq: 0
      stamp:
        secs: 0
        nsecs:         0
      frame_id: 'map'
    pose:
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  -
    header:
      seq: 1
      stamp:
        secs: 0
        nsecs:         0
      frame_id: 'map'
    pose:
      position:
        x: 1.5
        y: 0.0
        z: 0.00562381744385
      orientation:
        x: 0.0
        y: 0.0
        z: -0.676247385954
        w: 0.736674604551
  -
    header:
      seq: 2
      stamp:
        secs: 0
        nsecs:         0
      frame_id: 'map' 
    pose: 
      position: 
        x: 1.5
        y: -3.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.701590993579
        w: 0.71257987463
  -
    header:
      seq: 3
      stamp:
        secs: 0
        nsecs:         0
      frame_id: 'map' 
    pose: 
      position: 
        x: 1.5
        y: -5.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.998898181377
        w: 0.0469299823397
  -
    header:
      seq: 4
      stamp:
        secs: 0
        nsecs:         0
      frame_id: 'map' 
    pose: 
      position: 
        x: -1.5
        y: -5.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.996777490883
        w: 0.080216168371





